---
-   id: todo
    name: Check for TODOs
    description: Block commit with TODOs without a ticket number.
    entry: todo.py
    language: script
    files: ''
    stages: [commit, push, manual]

-   id: generated-sidecar
    name: Check for Generated Sidecars
    description: Block commit if sidecar files are not generated.
    entry: sidecar.py
    language: script
    always_run: true
    pass_filenames: false
    files: ''
    stages: [commit, push]
