---
-   id: todo
    name: Check for TODOs
    description: Block commit with TODOs without a ticket number.
    entry: todo.py
    language: script
    files: ''
    stages: [pre-commit, pre-push, manual]

-   id: regex
    name: Search for disallowed text
    description: Block commit when regex is found, like a TODO without a ticket number
    entry: todo.py
    language: script
    files: ''
    stages: [pre-commit, pre-push, manual]

-   id: generated-sidecar
    name: Check for Generated Sidecars
    description: Block commit if sidecar files are not generated.
    entry: sidecar.py
    language: script
    always_run: true
    pass_filenames: false
    files: ''
    stages: [pre-commit, pre-push]
